### ISSUE TITLE
add readme

### ISSUE THREAD

**Issue by RishabhJain2018** [pythonindia/junction-client#1]

**Comment by navyad** [comment]
@kracekumar I guess we can make separate class unit to handle the API request, which in isolation keep track of exposed URLs , request method, response and related stuff to request.

**Comment by kracekumar** [comment]
This is still work in progress and not yet complete. Refactoring is on the way.

**Comment by RishabhJain2018** [comment]
@kracekumar Please open the issues so that I can work upon.

**Comment by kracekumar** [comment]
@RishabhJain2018 There is no issue as of now.

**Comment by RishabhJain2018** [comment]
@kracekumar ok.
